version: "3.8"

services:
  cardinal-voting:
    # Use the pre-built image instead of building
    image: cardinal-voting:latest
    ports:
      - "${EXTERNAL_PORT:-8000}:8000"
    environment:
      # These will use values from .env file, with fallbacks if not set
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - DEBUG=${DEBUG:-false}
      - DATABASE_PATH=${DATABASE_PATH:-/app/data/votes.db}
      - CARDINAL_ENV=${CARDINAL_ENV:-production}
      # Admin credentials - MUST be set in .env file!
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-cardinal_admin_2025}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY:-cardinal_secret_key_change_in_production_123456789}
      # CORS settings for production
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://cardinal.tiarkaerell.com}
    volumes:
      # Persistent storage for database
      - cardinal_data:/app/data
      # Persistent storage for logs
      - cardinal_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - cardinal-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  cardinal_data:
    driver: local
  cardinal_logs:
    driver: local

networks:
  cardinal-network:
    driver: bridge
