"""add_user_id_to_voter_responses

Revision ID: 3f871632aa93
Revises: 8d1480278da2
Create Date: 2025-09-08 13:56:19.781013

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f871632aa93"
down_revision: str | Sequence[str] | None = "8d1480278da2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("voter_responses", sa.Column("user_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("idx_voter_responses_unique"), table_name="voter_responses")
    op.create_index(
        "idx_voter_responses_ip_unique",
        "voter_responses",
        ["vote_id", "voter_ip"],
        unique=True,
    )
    op.create_index(
        "idx_voter_responses_user_id", "voter_responses", ["user_id"], unique=False
    )
    op.create_index(
        "idx_voter_responses_user_unique",
        "voter_responses",
        ["vote_id", "user_id"],
        unique=True,
    )
    op.create_foreign_key(
        None, "voter_responses", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "voter_responses", type_="foreignkey")
    op.drop_index("idx_voter_responses_user_unique", table_name="voter_responses")
    op.drop_index("idx_voter_responses_user_id", table_name="voter_responses")
    op.drop_index("idx_voter_responses_ip_unique", table_name="voter_responses")
    op.create_index(
        op.f("idx_voter_responses_unique"),
        "voter_responses",
        ["vote_id", "voter_ip"],
        unique=True,
    )
    op.drop_column("voter_responses", "user_id")
    # ### end Alembic commands ###
